ET_MODEL_NAME = "PTJPL"
DEFAULT_VIIRS_DOWNLOAD_DIRECTORY = "VIIRS_download_directory"
DEFAULT_VIIRS_OUTPUT_DIRECTORY = "VIIRS_output"
DEFAULT_RESAMPLING = "cubic"
DEFAULT_PREVIEW_QUALITY = 20
DEFAULT_DOWNSCALE_AIR = False
DEFAULT_DOWNSCALE_HUMIDITY = False
DEFAULT_DOWNSCALE_MOISTURE = False
DEFAULT_COARSE_CELL_SIZE = 27375
DEFAULT_TARGET_VARIABLES = ["LE", "ET", "ESI"]
FLOOR_TOPT = True

DEFAULT_GFS_DOWNLOAD_DIRECTORY = "~/data/GFS"
DEFAULT_GFS_OUTPUT_DIRECTORY = "~/data/VIIRS-GFS-ET"
DEFAULT_VIIRS_DOWNLOAD_DIRECTORY = "~/data/VIIRS_download_directory"
VNP21A1D_DOWNLOAD_DIRECTORY = "~/data/VNP21A1D"
VNP09GA_DOWNLOAD_DIRECTORY = "~/data/VNP09GA"
DEFAULT_RESAMPLING = "cubic"
DEFAULT_PREVIEW_QUALITY = 20
GFS_CELL_SIZE = 27375
DEFAULT_TARGET_VARIABLES = ["LE", "ET", "ESI"]

DEFAULT_DOWNSCALE_AIR = False
DEFAULT_DOWNSCALE_HUMIDITY = False
DEFAULT_DOWNSCALE_MOISTURE = False


ET_MODEL_NAME = "PTJPLSM"
SWIN_MODEL_NAME = "GEOS5FP"
RN_MODEL_NAME = "Verma"

DOWNSCALE_AIR = False
DOWNSCALE_HUMIDITY = False
DOWNSCALE_MOISTURE = False
FLOOR_TOPT = True

USE_VIIRS_COMPOSITE = True
VIIRS_COMPOSITE_DAYS = 8

HLS_CELL_SIZE = 30
I_CELL_SIZE = 500
M_CELL_SIZE = 1000
GEOS5FP_CELL_SIZE = 27375
# GFS_CELL_SIZE = 54750
GFS_CELL_SIZE = 27375
LANDSAT_INITIALIZATION_DAYS = 16
HLS_INITIALIZATION_DAYS = 10

SAVE_INTERMEDIATE = False
SHOW_DISTRIBUTION = True
LOAD_PREVIOUS = False

VIIRS_GEOS5FP_OUTPUT_DIRECTORY = "VIIRS_GEOS5FP_VermaRn_PTJPLSMboostedToptET_1km_output"

TARGET_VARIABLES = [
    "Rn",
    "LE",
    "ET",
    "ESI",
    "SM",
    "ST",
    "Ta",
    "RH",
    "SWin",
    "VPD",
    "fg",
    "fM",
    "fSM",
    "fT",
    "fREW",
    "fTREW",
    "fTRM",
    "Topt"
]

ET_MODEL_NAME = "PTJPLSM"

VIIRS_DOWNLOAD_DIRECTORY = "VIIRS_download"
VIIRS_PRODUCTS_DIRECTORY = "VIIRS_products"
VIIRS_GEOS5FP_OUTPUT_DIRECTORY = "VIIRS_GEOS5FP_output"

USE_VIIRS_COMPOSITE = True
VIIRS_COMPOSITE_DAYS = 0

DEFAULT_RESAMPLING = "cubic"
DEFAULT_PREVIEW_QUALITY = 20
DEFAULT_DOWNSCALE_AIR = False
DEFAULT_DOWNSCALE_HUMIDITY = False
DEFAULT_DOWNSCALE_MOISTURE = False
DEFAULT_COARSE_CELL_SIZE = 27375
DEFAULT_TARGET_VARIABLES = ["LE", "ET", "ESI"]


ET_MODEL_NAME = "PTJPLSM"
SWIN_MODEL_NAME = "GEOS5FP"
RN_MODEL_NAME = "Verma"

FLOOR_TOPT = True

DOWNSCALE_AIR = False
DOWNSCALE_HUMIDITY = False
DOWNSCALE_MOISTURE = False

USE_VIIRS_COMPOSITE = True
VIIRS_COMPOSITE_DAYS = 8

HLS_CELL_SIZE = 30
I_CELL_SIZE = 500
M_CELL_SIZE = 1000
GEOS5FP_CELL_SIZE = 27375
# GFS_CELL_SIZE = 54750
GFS_CELL_SIZE = 27375
LANDSAT_INITIALIZATION_DAYS = 16
HLS_INITIALIZATION_DAYS = 10

TARGET_VARIABLES = [
    "Rn",
    "LE",
    "ET",
    "ESI",
    "SM",
    "ST",
    "Ta",
    "RH",
    "SWin"
]

ET_MODEL_NAME = "PTJPLSM"
SWIN_MODEL_NAME = "GEOS5FP"
RN_MODEL_NAME = "Verma"

FLOOR_TOPT = True

DOWNSCALE_AIR = False
DOWNSCALE_HUMIDITY = False
DOWNSCALE_MOISTURE = False

USE_VIIRS_COMPOSITE = True
VIIRS_COMPOSITE_DAYS = 8

HLS_CELL_SIZE = 30
I_CELL_SIZE = 500
M_CELL_SIZE = 1000
GEOS5FP_CELL_SIZE = 27375
# GFS_CELL_SIZE = 54750
GFS_CELL_SIZE = 27375
LANDSAT_INITIALIZATION_DAYS = 16
HLS_INITIALIZATION_DAYS = 10

TARGET_VARIABLES = [
    "Rn",
    "LE",
    "ET",
    "ESI",
    "SM",
    "ST",
    "Ta",
    "RH",
    "SWin"
]
