ET_MODEL_NAME = "PTJPL"
SWIN_MODEL_NAME = "GEOS5FP"
RN_MODEL_NAME = "Verma"

VIIRS_DOWNLOAD_DIRECTORY = "~/data/VIIRS_download_directory"
GFS_DOWNLOAD_DIRECTORY = "~/data/GFS"
GFS_OUTPUT_DIRECTORY = "~/data/VIIRS-GFS-ET"
VNP21A1D_DOWNLOAD_DIRECTORY = "~/data/VNP21A1D"
VNP09GA_DOWNLOAD_DIRECTORY = "~/data/VNP09GA"

VIIRS_DOWNLOAD_DIRECTORY = "VIIRS_download"
VIIRS_PRODUCTS_DIRECTORY = "VIIRS_products"
VIIRS_GEOS5FP_OUTPUT_DIRECTORY = "VIIRS_GEOS5FP_output"
VIIRS_GEOS5FP_OUTPUT_DIRECTORY_ALT = "VIIRS_GEOS5FP_VermaRn_PTJPLboostedToptET_1km_output"

RESAMPLING = "cubic"
PREVIEW_QUALITY = 20

DOWNSCALE_AIR = True
DOWNSCALE_HUMIDITY = False
DOWNSCALE_MOISTURE = True

MESO_CELL_SIZE = 500
COARSE_CELL_SIZE = 27375
GFS_CELL_SIZE = 27375
GEOS5FP_CELL_SIZE = 27375
HLS_CELL_SIZE = 30
I_CELL_SIZE = 500
M_CELL_SIZE = 1000

LANDSAT_INITIALIZATION_DAYS = 16
HLS_INITIALIZATION_DAYS = 10

TARGET_VARIABLES = ["LE", "ET", "ESI"]

FLOOR_TOPT = True

USE_VIIRS_COMPOSITE = True
VIIRS_COMPOSITE_DAYS = 8

SAVE_INTERMEDIATE = False
SHOW_DISTRIBUTION = True
LOAD_PREVIOUS = False