# Model Names
ET_MODEL_NAME = "PTJPL"
SWIN_MODEL_NAME = "GEOS5FP"
RN_MODEL_NAME = "Verma"

# Directory Paths
STATIC_DIRECTORY = "~/data/PTJPL_static"
SRTM_DIRECTORY = "~/data/SRTM_download_directory"
VIIRS_DIRECTORY = "~/data/VIIRS_download_directory"
GEOS5FP_DIRECTORY = "~/data/GEOS5FP_download_directory"
GFS_DIRECTORY = "~/data/GFS_download_directory"
VIIRS_DOWNLOAD_DIRECTORY = "~/data/VIIRS_download_directory"
GFS_DOWNLOAD_DIRECTORY = "~/data/GFS"
GFS_OUTPUT_DIRECTORY = "~/data/VIIRS-GFS-ET"
VNP21A1D_DOWNLOAD_DIRECTORY = "~/data/VNP21A1D"
VNP09GA_DOWNLOAD_DIRECTORY = "~/data/VNP09GA"
DEFAULT_LANDSAT_DOWNLOAD_DIRECTORY = "~/data/Landsat_download"
DEFAULT_LANDSAT_OUTPUT_DIRECTORY = "~/data/Landsat_output"

# Output/Product Directories (relative)
VIIRS_PRODUCTS_DIRECTORY = "VIIRS_products"
VIIRS_GEOS5FP_OUTPUT_DIRECTORY = "VIIRS_GEOS5FP_output"
VIIRS_GEOS5FP_OUTPUT_DIRECTORY_ALT = "VIIRS_GEOS5FP_VermaRn_PTJPLboostedToptET_1km_output"

# Resampling and Quality
DEFAULT_RESAMPLING = "cubic"
RESAMPLING = "cubic"
PREVIEW_QUALITY = 20

# Downscaling Options
DOWNSCALE_AIR = True
DOWNSCALE_HUMIDITY = True
DOWNSCALE_MOISTURE = True

# Cell Sizes (meters)
HLS_CELL_SIZE = 30
I_CELL_SIZE = 500
M_CELL_SIZE = 1000
GEOS5FP_CELL_SIZE = 27375
GFS_CELL_SIZE = 27375
MESO_CELL_SIZE = 500
COARSE_CELL_SIZE = 27375

# Initialization Days
LANDSAT_INITIALIZATION_DAYS = 16
HLS_INITIALIZATION_DAYS = 10
VIIRS_COMPOSITE_DAYS = 8

# Target Variables
TARGET_VARIABLES = ["LE", "ET", "ESI"]

# flags
FLOOR_TOPT = True
USE_VIIRS_COMPOSITE = True
SAVE_INTERMEDIATE = False
SHOW_DISTRIBUTION = True
LOAD_PREVIOUS = False