from typing import Union
from os.path import abspath, expanduser, join
from dateutil import parser
from datetime import date, datetime

from .generate_VIIRS_GEOS5FP_output_directory import generate_VIIRS_GEOS5FP_output_directory

def generate_VIIRS_GEOS5FP_output_filename(
        VIIRS_GEOS5FP_output_directory: str,
        target_date: Union[date, str],
        time_UTC: Union[datetime, str],
        target: str,
        product: str):
    """
    Generate the full output filename for a VIIRS-GEOS5FP product.

    Args:
        VIIRS_GEOS5FP_output_directory (str): Base directory for output files.
        target_date (Union[date, str]): The target date as a date object or ISO string.
        time_UTC (Union[datetime, str]): The UTC time as a datetime object or ISO string.
        target (str): The target region or identifier.
        product (str): The product name or type.

    Returns:
        str: The absolute path to the output file, including the filename.

    The filename is constructed as:
        VIIRS-GEOS5FP_{YYYY.MM.DD.HH.MM.SS}_{target}_{product}.tif
    and placed in the directory generated by generate_VIIRS_GEOS5FP_output_directory.
    """
    # Parse target_date if it's a string
    if isinstance(target_date, str):
        target_date = parser.parse(target_date).date()

    # Parse time_UTC if it's a string
    if isinstance(time_UTC, str):
        time_UTC = parser.parse(time_UTC)

    # Generate the output directory path
    directory = generate_VIIRS_GEOS5FP_output_directory(
        VIIRS_GEOS5FP_output_directory=VIIRS_GEOS5FP_output_directory,
        target_date=target_date,
        target=target
    )

    # Construct the output filename with the specified format
    filename = join(directory, f"VIIRS-GEOS5FP_{time_UTC:%Y.%m.%d.%H.%M.%S}_{target}_{product}.tif")

    return filename